#ifndef INC_11_ADVANCED_FUNCTION_CONCEPTS_CHALLENGES_H
#define INC_11_ADVANCED_FUNCTION_CONCEPTS_CHALLENGES_H

int main_variadic_functions();
int main_recursion();

#endif //INC_11_ADVANCED_FUNCTION_CONCEPTS_CHALLENGES_H
